const ROLE = {
  VENDOR_SUPER_ADMIN: 'VENDOR_SUPER_ADMIN',
  VENDOR_MONITORING_USER: 'VENDOR_MONITORING_USER',
  DEPARTMENT_SUPER_ADMIN: 'DEPARTMENT_SUPER_ADMIN',
  DEPARTMENT_ADMIN: 'DEPARTMENT_ADMIN',
  LOCATION_ADMIN: 'LOCATION_ADMIN',
  OPERATOR: 'OPERATOR',
  VIEWER: 'VIEWER',
  AUDITOR: 'AUDITOR',
  THIRD_PARTY_MONITORING: 'THIRD_PARTY_MONITORING'
};

const PERMISSIONS = {
  VIEW_DASHBOARD: new Set(Object.values(ROLE)),
  MUTE_ALARM: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.VENDOR_MONITORING_USER,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.OPERATOR,
    ROLE.THIRD_PARTY_MONITORING
  ]),
  FORCE_CLEAR: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.OPERATOR,
    ROLE.THIRD_PARTY_MONITORING
  ]),
  DRY_RUN: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.VENDOR_MONITORING_USER,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.OPERATOR,
    ROLE.THIRD_PARTY_MONITORING
  ]),
  RUN_ADMIN_JOB: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN
  ]),
  MANAGE_DEVICE_CONFIG: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN
  ]),
  MANAGE_USER_ACCESS: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN
  ])
};

module.exports = {
  ROLE,
  PERMISSIONS
};
