const ROLE = {
  VENDOR_SUPER_ADMIN: 'VENDOR_SUPER_ADMIN',
  VENDOR_MONITORING_USER: 'VENDOR_MONITORING_USER',
  DEPARTMENT_SUPER_ADMIN: 'DEPARTMENT_SUPER_ADMIN',
  DEPARTMENT_ADMIN: 'DEPARTMENT_ADMIN',
  LOCATION_ADMIN: 'LOCATION_ADMIN',
  OPERATOR: 'OPERATOR',
  VIEWER: 'VIEWER',
  AUDITOR: 'AUDITOR',
  THIRD_PARTY_MONITORING_USER: 'THIRD_PARTY_MONITORING_USER',
  // Backward compatibility with earlier naming used in this codebase.
  THIRD_PARTY_MONITORING: 'THIRD_PARTY_MONITORING_USER'
};

const PERMISSIONS = {
  VIEW_DASHBOARD: new Set(Object.values(ROLE)),
  MUTE_ALARM: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.VENDOR_MONITORING_USER,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.OPERATOR,
    ROLE.THIRD_PARTY_MONITORING_USER
  ]),
  FORCE_CLEAR: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.OPERATOR,
    ROLE.THIRD_PARTY_MONITORING_USER
  ]),
  DRY_RUN: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.VENDOR_MONITORING_USER,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.OPERATOR,
    ROLE.THIRD_PARTY_MONITORING_USER
  ]),
  RUN_ADMIN_JOB: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN
  ]),
  MANAGE_DEVICE_CONFIG: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN
  ]),
  MANAGE_USER_ACCESS: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN
  ]),
  RAISE_COMPLAINT: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.VENDOR_MONITORING_USER,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.OPERATOR,
    ROLE.VIEWER,
    ROLE.AUDITOR,
    ROLE.THIRD_PARTY_MONITORING_USER
  ]),
  VIEW_COMPLAINT: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.VENDOR_MONITORING_USER,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.OPERATOR,
    ROLE.VIEWER,
    ROLE.AUDITOR,
    ROLE.THIRD_PARTY_MONITORING_USER
  ]),
  UPDATE_COMPLAINT: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.VENDOR_MONITORING_USER,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.OPERATOR,
    ROLE.VIEWER,
    ROLE.THIRD_PARTY_MONITORING_USER
  ]),
  ACKNOWLEDGE_COMPLAINT: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.VENDOR_MONITORING_USER,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN
  ]),
  ASSIGN_COMPLAINT: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN
  ]),
  RESOLVE_COMPLAINT: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN
  ]),
  CLOSE_COMPLAINT: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN
  ]),
  MANAGE_DEVICE_LIFECYCLE: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN
  ]),
  EXPORT_AUDIT_REPORT: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.VENDOR_MONITORING_USER,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.AUDITOR
  ]),
  MANAGE_HEAD_OFFICE_INTEGRATION: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN
  ]),
  RESET_USER_PASSWORD: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN
  ]),
  CHANGE_OWN_PASSWORD: new Set([
    ROLE.VENDOR_SUPER_ADMIN,
    ROLE.VENDOR_MONITORING_USER,
    ROLE.DEPARTMENT_SUPER_ADMIN,
    ROLE.DEPARTMENT_ADMIN,
    ROLE.LOCATION_ADMIN,
    ROLE.OPERATOR,
    ROLE.VIEWER,
    ROLE.AUDITOR,
    ROLE.THIRD_PARTY_MONITORING_USER
  ])
};

module.exports = {
  ROLE,
  PERMISSIONS
};
